name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust setup
        run: rustup toolchain install stable --profile minimal
      - name: Install PGRX
        run: cargo install --locked cargo-pgrx
      - name: Linting
        run: cargo clippy

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        pg-version: ["12", "13", "14", "15", "16", "17"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Rust setup
        run: rustup toolchain install stable --profile minimal
      - name: Install PGRX
        run: cargo install --locked cargo-pgrx
      - name: Setup PGRX
        run: cargo pgrx init
      - name: Run tests
        run: cargo pgrx test pg${{ matrix.pg-version }}
