name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust setup
        run: rustup toolchain install stable --profile minimal
      - name: Linting
        run: cargo clippy

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        pg-version: ["12", "13", "14", "15", "16", "17"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Rust setup
        run: rustup toolchain install stable --profile minimal
      - name: Run tests
        run: cargo test
